Module1-task1
htmlacademy-php/2070137-yeticave-12 pull request #1
Opened 2022-03-31 08:28 UTC by AlexandrMag

2022-03-31 09:03 UTC, esbobkov requested changes

2022-03-31 09:03 UTC, esbobkov commented on Readme.md
> +* Наставник: [Евгений Бобков].
В таком случае стоит добавить `(https://up.htmlacademy.ru/php/12/user/2016291)` чтобы это выглядело как ссылка. Иначе здесь только половина формотирования)

2022-04-01 09:31 UTC, AlexandrMag commented on Readme.md
> +* Наставник: [Евгений Бобков].
Добавил

2022-04-01 10:48 UTC, esbobkov approved these changes
:ok:

2022-04-01 10:48 UTC, merged